batch_inference: 48
split_batch_in: 8
batch_size: 8
batches_epoch: 300
epochs: 300
eta: 3
hidden_size: 64
loss_fn: l1_loss
lr: 0.0008
lr_scheduler: magic
message_layers: 1
model_name: 'PGUTS'
n_layers: 5
norm: true
patience: 40
precision: 16
reweight: softmax
scale_target: false
spatial_aggr: softmax
stride: 1
update_z_cross: false
val_len: 0.1
whiten_prob:
- 0.2
- 0.5
- 0.8
window: 24
time_count: 1
space_count: 0
factor_s: []
factor_t: [3, 6]
n_heads: 4
ts_order: True
use_pg_enc: True
wand_on: True

